baseURL = "http://test-hugo.org/"
languageCode = "fr-FR"
title = "My New Hugo Site"
theme = "hugo-theme-dopetrope-master"


[params.portfolio]
    title = "My Portfolio"
    foldername = "portfolio"
    findoutmoretext = "Find out more"

[params.blog]
    title = "The Blog"
    viewalltext = "View All"
    foldername = "blog"

[params.settings]
    googleanalytics = "UA-113904582-1"
    disqus = "hugo-dopetrope"
